# -*- coding: utf-8 -*-
"""Python project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LrlYSnt9YfsER9eKT1WqqHY2AvWEM8-d

Data Analytics in Python Project
Michael Campanelli

There are three main things that I wanted to look at when I imported this data. The first is I wanted to see how my fathers high school is currently doing on there regents exam. For this part of the project I was really looking for the mean scores over the last couple of years. The next thig was I wanted to compaire how other schools have done in  there US history regents. Finally I was a bit confused as to why there was grades K-8 tking regents exams designed for high school students but I wanted to see how the mean of these students is.
"""

import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')
df
#Implorting fuctions and the data set
##Here I just wanted to take a quick look at the data set to try and get an idea 
##of what I want to compaire

df.groupby(['School Name'])['Regents Exam'].count()

filt = (df['School Name'] == 'James Madison High School') & (df['Regents Exam'] == 'U.S. History and Government')
df.replace('s','nan')
df[filt]
#The first thing I wanted to look at was US History regents scores for James Madison high school. James Madison was the school my dad 
#went to and with history being my favorite subject I wanted to take a further look into this.

sns.displot(df[filt]['Mean Score'], bins = 50)
#Here I ploted out the mean scores compaired to the frequency that those score occured

y = (df['Mean Score'] > '82') & (df['Regents Exam'] == 'U.S. History and Government') & (df['School Level'] == 'High school')
df[y]
#The second Thing that I wanted to look at was the mean scores of the US history regents that were above an average of 75. 
#My goal with this was to determine which school had the highest average scores

sns.jointplot(x='Mean Score', y= 'School Name', data = df[y], kind= 'scatter')
#This graph shows the mean scores based on the high school

z = (df['School Level'] == 'K-8')
df[z]
#When going through the data I was curious about why there was regents data for grades K-8. The point of this data set is
#to look at what regents these grades are taking

sns.jointplot(x= 'Regents Exam', y= 'Total Tested', data = df[z])